version: '3.9'
x-lazycat-app:
  id: seafile
  version: 1.0.0
  quality: normal
  icon: icon.png
  title: Seafile
  summary: 一套用于创建网络硬盘的客户端－服务器软件
  postInstallMessage: "默认用户名: me@example.com，密码: asecret"
  screenshots:
    - screenshot.jpg
  ingress:
    - service:   seafile
      port:      80
      subdomain: seafile
  categories:
    - files
services:
  db:
    image: mariadb:10.5
    container_name: seafile-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=db_dev  # Requested, set the root's password of MySQL service.
      - MYSQL_LOG_CONSOLE=true
    volumes:
      - db:/var/lib/mysql  # Requested, specifies the path to MySQL data persistent store.
    networks:
      - seafile-net

  memcached:
    image: memcached:1.5.6
    container_name: seafile-memcached
    entrypoint: memcached -m 256
    networks:
      - seafile-net
          
  seafile:
    image: seafileltd/seafile-mc:8.0.7
    container_name: seafile
#    ports:
#      - "80:80"
#     - "443:443"  # If https is enabled, cancel the comment.
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./setup-seafile-mysql.py:/opt/seafile/seafile-server-8.0.7/setup-seafile-mysql.py.out
      - ./enterpoint.sh:/scripts/enterpoint.sh
      - seafile-data:/shared   # Requested, specifies the path to Seafile data persistent store.
    environment:
      - DB_HOST=db
      - DB_ROOT_PASSWD=db_dev  # Requested, the value shuold be root's password of MySQL service.
      - TIME_ZONE=Etc/UTC  # Optional, default is UTC. Should be uncomment and set to your local time zone.
      - SEAFILE_ADMIN_EMAIL=me@example.com # Specifies Seafile admin user, default is 'me@example.com'.
      - SEAFILE_ADMIN_PASSWORD=asecret     # Specifies Seafile admin password, default is 'asecret'.
      - SEAFILE_SERVER_LETSENCRYPT=false   # Whether to use https or not.
      - SEAFILE_SERVER_HOSTNAME=${LAZYCAT_APP_ORIGIN} # Specifies your host name if https is enabled.
    depends_on:
      - db
      - memcached
    networks:
      - seafile-net
volumes:
  db:
  seafile-data:
networks:
  seafile-net:
