version: '3'

services:
  showdoc:
    image: star7th/showdoc
    container_name: showdoc
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./showdoc_data/html:/var/www/html/
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=showdoc123
      - MYSQL_DB_NAME=showdoc
      - INSTALL_DATA=1
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=showdoc123
      - MYSQL_DATABASE=showdoc
    volumes:
      - ./mysql_data:/var/lib/mysql